name: Mention Users on Specific File Change in PR

on:
  pull_request:

jobs:
  mention-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Read configuration and mention users
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            
            // Read the configuration file
            const configPath = '.github/notify-config.json';
            const configFile = fs.readFileSync(configPath, 'utf8');
            const config = JSON.parse(configFile);
            
            // Extract PR number
            const prNumber = context.issue.number; // Correct way to get PR number
            
            // Async function to handle API calls and logic
            async function run() {
              // Fetch list of files changed in the PR
              const listFilesResponse = await github.rest.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
              const changedFiles = listFilesResponse.data.map(file => file.filename);
              
              let message = "Changes have been detected in:";
              
              // Initialize a flag to check if any file was mentioned
              let hasMentionedFiles = false;
              
              // Check if the PR contains changes to the files specified in the configuration
              for (const file of config.files_to_watch) {
                if (changedFiles.some(changedFile => changedFile === file.path)) {
                  // Construct the mention message
                  const usersToMention = file.users.join(' ');
                  message += `\n- '${file.path}'. Pinging ${usersToMention} for review.`;
                  hasMentionedFiles = true;
                }
              }
              
              // Post the comment on the PR if there are any files to mention
              if (hasMentionedFiles) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: message
                });
              } else {
                console.log("No configured files were changed in this PR.");
              }
            }
            
            // Execute the async function
            run().catch(err => core.setFailed(`Unhandled error: ${err}`));


